django/iotflash/iotflash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

handler404 = views.error_404

django/iotflash/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
            path('', views.IndexView.as_view(), name='index'),
            path('statistics/', views.StatisticsView.as_view(), name="statistics"),
            path('<int:pk>/', views.details_redirect),
            path('<int:pk>/details/', views.DetailsView.as_view(), name="details"),
            path('management/', views.ManagementView.as_view(), name="management"),
            path('changeresult/', views.ChangeResultView.as_view(), name="changeresult"),
            path('<int:node_id>/changename/', views.changename, name="changename"),
            ]

django/iotflash/main/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Node(models.Model):
    mac_address = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    creation_date = models.DateTimeField(default=datetime.now)
    def __str__(self):
        return self.name + " / " + self.mac_address
    class Meta:
        db_table = "node"

class Data(models.Model):
    node = models.ForeignKey(Node, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=datetime.now)
    value = models.IntegerField()
    def __str__(self):
        return self.node.name + " / " + self.node.mac_address + ": " + str(self.value)
    class Meta:
       db_table = "data"

django/iotflash/main/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.urls import reverse
from django.views import generic
from .models import *

def error_404(request, exception):
    return render(request, 'main/error_404.html', {}, status=404)

class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'nodes'
    def get_queryset(self):
        return Node.objects.order_by('id')

class StatisticsView(generic.ListView):
    template_name = 'main/statistics.html'
    context_object_name = 'data'
    def get_queryset(self):
        return Data.objects.all()

def details_redirect(request, pk):
    return HttpResponseRedirect(reverse('main:details', args={pk}))

class DetailsView(generic.DetailView):
    model = Node
    template_name = 'main/details.html'

class ManagementView(generic.ListView):
    template_name = 'main/management.html'
    context_object_name = 'nodes'
    def get_queryset(self):
        return Node.objects.order_by('id')
    
def changename(request, node_id):
    try:
        node = Node.objects.get(pk=node_id)
        newName = request.POST['nodename']
        if(not newName or newName.isspace()):
            return HttpResponseRedirect(reverse('main:details', args={node_id}))
        node.name = newName
        node.save()
        return HttpResponseRedirect(reverse('main:changeresult'))
    except Node.DoesNotExist:
        return render(request, 'main/error_404.html', {}, status=404)

class ChangeResultView(generic.TemplateView):
        template_name = 'main/changeresult.html'

django/iotflash/main/templates/main/changename.html
<p>Your name was changed!</p>

django/iotflash/main/templates/main/changeresult.html
<meta http-equiv="refresh" content="3;url={% url 'main:index' %}" />

<p>Success! (Redirect in 3 seconds)</p>

django/iotflash/main/templates/main/details.html
<head><title>Details</title></head>
<p>ID: {{node.id}}</p>
<p>Name: {{node.name}}</p>
<p>Mac: {{node.mac_address}}</p>

<p>Change the name of this node:</p>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'main:changename' node.id %}" method="post">
	{% csrf_token %}
	<input type="text" name="nodename" id="nodename" />
	<input type="submit" value="Change Name" />
</form>

django/iotflash/main/templates/main/error_404.html
<head><title>Error 404</title></head>

<h1><center>ERROR 404</center></h1>
<br>

<center>This page does not exist.</center>

<center><a href="{% url 'main:index' %}">Back to index</a></center>

django/iotflash/main/templates/main/index.html
<head><title>IoTFlash</title></head>
{% if nodes %}
<p>Nodes:</p>
<ul>
	{% for node in nodes %}
	<li><a href="{% url 'main:details' node.id %}">{{node.name}}</a></li>
	{% endfor %}
</ul>

{% else %}
<p>No nodes available</p>
{% endif %}

<p><a href="{% url 'main:statistics' %}">Statistics</a></p>
<p><a href="{% url 'main:management' %}">Management</a></p>

django/iotflash/main/templates/main/management.html
<p>Configuration options for the lucster. Remove devices, turn devices off temporarily, rotate device keys, etc.</p>

django/iotflash/main/templates/main/statistics.html
<p>This is where we look at overally statistics about all nodes: Creation date, metadata (how much data, etc.).</p>